/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visualkrisnarizkid;

/**
 *
 * @author krisn
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Latihan1 = new javax.swing.JButton();
        Latihan2 = new javax.swing.JButton();
        Latihan3 = new javax.swing.JButton();
        Latihan4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Pemrograman teks grafis & multimedia");

        Latihan1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Latihan1.setText("Latihan1");
        Latihan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Latihan1ActionPerformed(evt);
            }
        });

        Latihan2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Latihan2.setText("Latihan2");
        Latihan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Latihan2ActionPerformed(evt);
            }
        });

        Latihan3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Latihan3.setText("Latihan3");
        Latihan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Latihan3ActionPerformed(evt);
            }
        });

        Latihan4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Latihan4.setText("Latihan4");
        Latihan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Latihan4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Latihan1)
                            .addComponent(Latihan3))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Latihan4)
                            .addComponent(Latihan2))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Latihan1)
                    .addComponent(Latihan2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Latihan3)
                    .addComponent(Latihan4))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Latihan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Latihan1ActionPerformed
        Latihan1 lat1 = new Latihan1(); 
        lat1.show(); // TODO add your handling code here:
    }//GEN-LAST:event_Latihan1ActionPerformed

    private void Latihan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Latihan2ActionPerformed
        Latihan2 lat2 = new Latihan2();
        lat2.show(); // TODO add your handling code here:
    }//GEN-LAST:event_Latihan2ActionPerformed

    private void Latihan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Latihan3ActionPerformed
        Latihan3 lat3 = new Latihan3();
        lat3.show(); // TODO add your handling code here:
    }//GEN-LAST:event_Latihan3ActionPerformed

    private void Latihan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Latihan4ActionPerformed
        Latihan4 lat4 = new Latihan4();
        lat4.show(); // TODO add your handling code here:
    }//GEN-LAST:event_Latihan4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Latihan1;
    private javax.swing.JButton Latihan2;
    private javax.swing.JButton Latihan3;
    private javax.swing.JButton Latihan4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
